business:
  name: Cooperativa d'Estellencs
db:
  name: espigol
  server: mongodb://localhost:27017
expenses:
  limits:
    "2026":
      current: 30000
      investment: 70000
files:
  logo: configs/logo.png
output:
  directory: ~/espigol/reports
server:
  port: 8080
urls:
  mongoexpress: http://localhost:8081/db/espigol
